### ISSUE TITLE
能分享下自定义数据的返回格式吗

### ISSUE THREAD

**Issue by xiaotianlu** [xinggengchang/grafana-plugin#1]
绘制中国地图时使用自定义数据，URL返回的数据格式，谢谢

**Comment by xinggengchang** [comment]
https://github.com/wuyi5630/grafana-echarts-panel

**Comment by xinggengchang** [comment]
> 绘制中国地图时使用自定义数据，URL返回的数据格式，谢谢

参考这个 https://github.com/wuyi5630/grafana-echarts-panel ，我在他基础上改的。

**Comment by xiaotianlu** [comment]
好的  谢谢
