### ISSUE TITLE
大佬 新疆显示不了数据

### ISSUE THREAD

**Issue by starsliao** [xinggengchang/grafana-plugin#4]
我看数据新疆是    Xinjiang Uyghur Autonomous Region	
但是在地图上显示NaN

![图片](https://user-images.githubusercontent.com/3349611/167245418-360b4048-b656-4fee-9c42-fc1c2cc5ce36.png)
![图片](https://user-images.githubusercontent.com/3349611/167245442-7f057443-520f-4427-926b-af1fcd2981cc.png)

能不能抢救一下？

**Comment by xinggengchang** [comment]
data_formatter.js 文件中做了一个中文和英文的转换，你可以在改改这个文件或者再加一个if
if (locationName === 'Xinjiang') return '新疆';

**Comment by starsliao** [comment]
感谢大佬  问题解决。
